### ISSUE TITLE
ERROR: UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by DAMIOTF** [tacheometry/steam-hour-farmer#3]
### **After entering Steam guard code. i getting this error ...**

![image](https://github.com/tacheometry/steam-hour-farmer/assets/78971014/74783e5f-2f47-42e6-aeaa-c3361513f953)

my `.env` file:

```
USERNAME="damiotv_official"
PASSWORD="**********"
GAMES="1091500"
```

**Comment by tacheometry** [comment]
I just updated the package, can you try to update and change the `.env` file like described in https://github.com/tacheometry/steam-hour-farmer/releases/tag/v2.0.0 ?

**Comment by DAMIOTF** [comment]
same error...

![image](https://github.com/tacheometry/steam-hour-farmer/assets/78971014/4a3e43c7-65f2-4a0d-8fe9-a76c49d14252)

```
ubuntu@damiotf:~$ nano .env
ubuntu@damiotf:~$ steam-hour-farmer
/usr/local/lib/node_modules/steam-hour-farmer/node_modules/steam-user/components/03-messages.js:740
                                machineId: this._logOnDetails?.machine_id
                                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/steam-hour-farmer/node_modules/steam-user/components/content_manifest.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
ubuntu@damiotf:~$
```

**Comment by tacheometry** [comment]
What is the output of `node -v`?

**Comment by DAMIOTF** [comment]
v12.22.9

**Comment by tacheometry** [comment]
You need Node.js version `>=16`. The LTS one should be fine - there's instructions in the project homepage. **But before you upgrade**, can you run `npm i -g steam-hour-farmer@latest` again? It should warn you this time

**Comment by DAMIOTF** [comment]
its working after update node.js, thank you :)
