### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by InstantName123** [tacheometry/steam-hour-farmer#7]
user@fbi-vps:~/steam$ steam-hour-farmer
/usr/local/lib/node_modules/steam-hour-farmer/node_modules/steam-user/components/03-messages.js:740
                                machineId: this._logOnDetails?.machine_id
                                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/steam-hour-farmer/node_modules/steam-user/components/content_manifest.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by InstantName123** [comment]
Latest version of NodeJS has been installed.

**Comment by tacheometry** [comment]
@InstantName123 Does it work now?

If not can you write the output of `node -v` to make sure it's working?
Also try restarting the machine

**Comment by tacheometry** [comment]
Re-open the issue if needing help 👍
